In [ ]:
import pandas as pd
import numpy as np
import math

file_path = r"C:\Users\Mihnea\Desktop\Veridion Project\incercare 4\project\data\BasicCompanyDataAsOneFile-2026-08-01.csv"

In [17]:
df = pd.read_csv(file_path, low_memory=False)
df.columns = df.columns.str.strip()
print(f"Rows: {len(df):,}   Columns: {len(df.columns)}")
df.head()

Rows: 5,695,465   Columns: 55

,CompanyName,CompanyNumber,RegAddress.CareOf,RegAddress.POBox,RegAddress.AddressLine1,RegAddress.AddressLine2,RegAddress.PostTown,RegAddress.County,RegAddress.Country,RegAddress.PostCode,...,PreviousName_7.CONDATE,PreviousName_7.CompanyName,PreviousName_8.CONDATE,PreviousName_8.CompanyName,PreviousName_9.CONDATE,PreviousName_9.CompanyName,PreviousName_10.CONDATE,PreviousName_10.CompanyName,ConfStmtNextDueDate,ConfStmtLastMadeUpDate
0,! LTD,08209948,NaN,NaN,9 PRINCES SQUARE,NaN,HARROGATE,NaN,ENGLAND,HG1 1ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25/09/2026,11/09/2025
1,!ABRIDGE TAX LTD,16092999,NaN,NaN,82 GREAT NORTH ROAD,GREAT NORTH BUSINESS CENTRE,HATFIELD,NaN,UNITED KINGDOM,AL9 5BL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/12/2026,20/11/2025
2,!BIG IMPACT GRAPHICS LIMITED,11743365,NaN,NaN,124 CITY ROAD,NaN,LONDON,NaN,NaN,EC1V 2NX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29/12/2026,15/12/2025
3,!FE NETWORK LIMITED,16873705,NaN,NaN,C/O AACSL ACCOUNTANT LIMITED,1ST FLOOR NORTH WESTGATE HOUSE,"HARLOW, ESSEX",NaN,UNITED KINGDOM,CM20 1YS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,08/12/2026,NaN
4,!NFLECTION ADVISORY LIMITED,15073164,NaN,NaN,74 SANTERS LANE,NaN,POTTERS BAR,HERTFORDSHIRE,ENGLAND,EN6 2DA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28/08/2026,14/08/2025

In [18]:
print(df.columns)

Index(['CompanyName', 'CompanyNumber', 'RegAddress.CareOf', 'RegAddress.POBox',
       'RegAddress.AddressLine1', 'RegAddress.AddressLine2',
       'RegAddress.PostTown', 'RegAddress.County', 'RegAddress.Country',
       'RegAddress.PostCode', 'CompanyCategory', 'CompanyStatus',
       'CountryOfOrigin', 'DissolutionDate', 'IncorporationDate',
       'Accounts.AccountRefDay', 'Accounts.AccountRefMonth',
       'Accounts.NextDueDate', 'Accounts.LastMadeUpDate',
       'Accounts.AccountCategory', 'Returns.NextDueDate',
       'Returns.LastMadeUpDate', 'Mortgages.NumMortCharges',
       'Mortgages.NumMortOutstanding', 'Mortgages.NumMortPartSatisfied',
       'Mortgages.NumMortSatisfied', 'SICCode.SicText_1', 'SICCode.SicText_2',
       'SICCode.SicText_3', 'SICCode.SicText_4',
       'LimitedPartnerships.NumGenPartners',
       'LimitedPartnerships.NumLimPartners', 'URI', 'PreviousName_1.CONDATE',
       'PreviousName_1.CompanyName', 'PreviousName_2.CONDATE',
       'PreviousName_2.CompanyName', 'PreviousName_3.CONDATE',
       'PreviousName_3.CompanyName', 'PreviousName_4.CONDATE',
       'PreviousName_4.CompanyName', 'PreviousName_5.CONDATE',
       'PreviousName_5.CompanyName', 'PreviousName_6.CONDATE',
       'PreviousName_6.CompanyName', 'PreviousName_7.CONDATE',
       'PreviousName_7.CompanyName', 'PreviousName_8.CONDATE',
       'PreviousName_8.CompanyName', 'PreviousName_9.CONDATE',
       'PreviousName_9.CompanyName', 'PreviousName_10.CONDATE',
       'PreviousName_10.CompanyName', 'ConfStmtNextDueDate',
       'ConfStmtLastMadeUpDate'],
      dtype='str')

In [19]:
df['Accounts.AccountCategory'].value_counts(dropna=False)

Accounts.AccountCategory
MICRO ENTITY                   1854785
NO ACCOUNTS FILED              1460776
TOTAL EXEMPTION FULL           1337636
DORMANT                         638939
UNAUDITED ABRIDGED              165477
FULL                             86759
SMALL                            68306
AUDIT EXEMPTION SUBSIDIARY       33862
GROUP                            28192
TOTAL EXEMPTION SMALL             8955
MEDIUM                            6384
ACCOUNTS TYPE NOT AVAILABLE       3793
AUDITED ABRIDGED                  1163
FILING EXEMPTION SUBSIDIARY        407
PARTIAL EXEMPTION                   28
INITIAL                              3
Name: count, dtype: int64

In [20]:
print(df['Accounts.AccountCategory'].value_counts().to_markdown())

| Accounts.AccountCategory    |   count |
|:----------------------------|--------:|
| MICRO ENTITY                | 1854785 |
| NO ACCOUNTS FILED           | 1460776 |
| TOTAL EXEMPTION FULL        | 1337636 |
| DORMANT                     |  638939 |
| UNAUDITED ABRIDGED          |  165477 |
| FULL                        |   86759 |
| SMALL                       |   68306 |
| AUDIT EXEMPTION SUBSIDIARY  |   33862 |
| GROUP                       |   28192 |
| TOTAL EXEMPTION SMALL       |    8955 |
| MEDIUM                      |    6384 |
| ACCOUNTS TYPE NOT AVAILABLE |    3793 |
| AUDITED ABRIDGED            |    1163 |
| FILING EXEMPTION SUBSIDIARY |     407 |
| PARTIAL EXEMPTION           |      28 |
| INITIAL                     |       3 |

In [21]:
df["CompanyStatus"].value_counts(dropna=False)

CompanyStatus
Active                                              5190464
Active - Proposal to Strike off                      388951
Liquidation                                          108797
In Administration                                      3739
Live but Receiver Manager on at least one charge       2119
Voluntary Arrangement                                   576
In Administration/Administrative Receiver               344
RECEIVERSHIP                                            182
ADMINISTRATION ORDER                                    121
ADMINISTRATIVE RECEIVER                                 105
In Administration/Receiver Manager                       54
RECEIVER MANAGER / ADMINISTRATIVE RECEIVER               10
VOLUNTARY ARRANGEMENT / RECEIVER MANAGER                  2
VOLUNTARY ARRANGEMENT / ADMINISTRATIVE RECEIVER           1
Name: count, dtype: int64

In [22]:
%pip install tabulate

Requirement already satisfied: tabulate in c:\Users\Mihnea\miniconda3\envs\data-science\Lib\site-packages (0.10.0)
Note: you may need to restart the kernel to use updated packages.

In [23]:
print(df['CompanyStatus'].value_counts().to_markdown())

| CompanyStatus                                    |   count |
|:-------------------------------------------------|--------:|
| Active                                           | 5190464 |
| Active - Proposal to Strike off                  |  388951 |
| Liquidation                                      |  108797 |
| In Administration                                |    3739 |
| Live but Receiver Manager on at least one charge |    2119 |
| Voluntary Arrangement                            |     576 |
| In Administration/Administrative Receiver        |     344 |
| RECEIVERSHIP                                     |     182 |
| ADMINISTRATION ORDER                             |     121 |
| ADMINISTRATIVE RECEIVER                          |     105 |
| In Administration/Receiver Manager               |      54 |
| RECEIVER MANAGER / ADMINISTRATIVE RECEIVER       |      10 |
| VOLUNTARY ARRANGEMENT / RECEIVER MANAGER         |       2 |
| VOLUNTARY ARRANGEMENT / ADMINISTRATIVE RECEIVER  |       1 |

In [24]:
df_active = df[df["CompanyStatus"] == "Active"].copy()
print(f"Active companies: {len(df_active):,} out of {len(df):,} total")

Active companies: 5,190,464 out of 5,695,465 total

In [25]:
N = len(df_active)
z = 1.96
p = 0.5

def sample_size(N, error):
    n = (N * z**2 * p * (1 - p)) / (error**2 * (N - 1) + z**2 * p * (1 - p))
    return math.ceil(n)

n5 = sample_size(N,0.05)
n7 = sample_size(N,0.07)
n10 = sample_size(N,0.10)

print(f"Population (active companies):{N:,}")
print(f"Sample size for 5%:{n5}")
print(f"Sample size for 7%:{n7}")
print(f"Sample size for 10%:{n10}")

Population (active companies):5,190,464
Sample size for 5%:385
Sample size for 7%:196
Sample size for 10%:97

In [26]:
sample = df_active.sample(n=100, replace=False, random_state=42)
print(sample.shape)
sample[["CompanyName", "CompanyNumber", "CompanyStatus"]].head(10)

(100, 55)

                         CompanyName CompanyNumber CompanyStatus
2352344              HOCKEY STOP LTD      12343252        Active
3681151         OAKSIDE VENTURES LTD      15802979        Active
4728472   SPIRAL CONSULTANTS LIMITED      08905847        Active
5349318            UTOP SERVICES LTD      17047762        Active
5094994  THE RECRUITMENT CONTACT LTD      15110088        Active
2282134      HEALTHWISE SUPPLIES LTD      16283354        Active
4094074            QDM MORTGAGES LTD      13587026        Active
5127126         THE ZOO HOLBROOK LTD      15863622        Active
2081544             GLW BUILDING LTD      14007666        Active
2846842                   KODIVA LTD      10901561        Active

In [27]:
sample.to_csv("../data/sample100.csv", index=False)
print("Saved to ../data/sample100.csv")

Saved to ../data/sample100.csv